################
### PROGRAMS ###
################

# https://wiki.hypr.land/Configuring/Keywords/

$terminal = foot
$fileManager = nautilus
$menu = fuzzel
$browser = zen-browser -p
$locker = hyprlock
