################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto


################
### PROGRAMS ###
################

source = ~/.config/hypr/configuration/programs.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/configuration/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/configuration/env.conf

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/configuration/style.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/configuration/input.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/configuration/keybindings.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

exec-once = ags

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
