################
### PROGRAMS ###
################

# See https://wiki.hyprland.org/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus
#$menu = wofi --conf ~/.config/wofi/config/config --style ~/.config/wofi/src/mocha/style.css --show drun
$menu = ags -t launcher
$browser = firefox
